//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;








class CEntityState
{


	private BitArray 		m_stateBit;


	public CEntityState()
	{
		m_stateBit 	= new BitArray ( (int)EState.ES_End );
	}


	//-----------------------------------------------------------------------------
	// 设置状态
	//-----------------------------------------------------------------------------
	public void SetState( EState nIndex )
	{
		int nIdx = (int)nIndex;
		m_stateBit [nIdx] = true;
	}

	//-----------------------------------------------------------------------------
	// 撤销状态
	//-----------------------------------------------------------------------------
	public void UnSetState( EState nIndex )
	{
		int nIdx = (int)nIndex;
		m_stateBit [nIdx] = false;
	}


	//-----------------------------------------------------------------------------
	// 查询状态
	//-----------------------------------------------------------------------------
	public bool IsInState( EState nIndex )
	{

		int nIdx = (int)nIndex;
		return m_stateBit [nIdx];
	}
}

