Util 			= Framework.Util;
LuaHelper 		= Framework.LuaHelper;
LuaBehaviour    = Framework.LuaBehaviour;
PanelManager    = LuaHelper.GetPanelManager();
LevelManager	= LuaHelper.GetLevelManager();
BundleManager   = LuaHelper.GetResManager();
NetworkManager	= LuaHelper.GetNetworkManager();
GameEventManager= LuaHelper.GetEventManager();
iTween			= Framework.iTween;